spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres.c8a58wttwocm.ap-northeast-2.rds.amazonaws.com
    username: postgres
    password: backbenew
  redis:
    host: localhost
    port: 5432

  mvc: # for swagger
    path match:
      matching-strategy:
        ant_path_matcher


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations: classpath*:data.sql
#      mode: always
#      platfrom: h2

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

server:
  error:
    include-stacktrace: never